baseURL: "https://brycelittlejohn.github.io" 
title: Bryce Littlejohn
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Research Group
          url: group
          weight: 1
        - name: Publications
          url: publications/
          weight: 2
        #- name: Projects
        #  url: projects/
        #  weight: 2

params:
    #TODO: Short description
    description: "I'm an Associate Professor of Physics at the Illinois Institute of Technology."
    author: Bryce Littlejohn
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Bryce Littlejohn
          #TODO: Introduction
          subtitle: "Howdy!
          
            <br> <br>
            I'm an Associate Professor of Physics at the Illinois Institute of Technology.

            <br> <br>
            I do cool Physics. Here’s a fun new LArTPC <ins>[result](https://arxiv.org/abs/2408.05133)</ins> from my group!
            "
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Bryce Littlejohn
          buttons:
            - name: Research Group
              url: group
            - name: Publications
              url: publications/
            #- name: Projects
            #  url: projects/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:blittlej@iit.edu 
        - name: Location
          url: location
        - name: INSPIRES-HEP
          url: https://inspirehep.net/authors/1191643
        #- name: GitHub
        #  url: https://github.com/mandri97

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "B. Littlejohn"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
